### ISSUE TITLE
No data displayed on dashboards

### ISSUE THREAD

**Issue by EvilGrinUK** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing_Dashboards_Beats#1]
Hi,

I am using the Graylog OVA for testing purposes. I have setup the graylog sidecar and winbeatlog and am successfully reciveing log entries into my Graylog VM. However when I view any of the AD dashboards there is no data displayed.

Thanks.

**Comment by zpfln** [comment]
I experienced the same thing and I noticed it had to do with that the fields name did not match. I have "winbeatlog_event_id" instead of "event_id" that the dashboard is asking for. I haven't resolved it...

**Comment by SoarinFerret** [comment]
@zpfln - In the instructions, it says to create `Beats input (with "Do not add Beats type as prefix" checked)`. If you do not check this, it will add the `winlogbeat_` prefix.

I have a forked copy of the code with a branch that supports the `winlogbeat_` prefix - https://github.com/SoarinFerret/Graylog_Content_Pack_Active_Directory_Auditing_Dashboards_Beats/tree/winlogbeat-prefix-compatible

**Comment by yoder731** [comment]
I have the box checked and I still receive messages with the winlogbeat_ prefix added. Not sure if I am missing something here. 

I ended up creating a pipeline rule that will replace winlogbeat_event_id with event_id.

**Comment by flotpg** [comment]
Hey,
thx for this content pack. Unfortunately it's not working correctly for me.
It seems the search strings are missing - it just counts all messages or am I wrong:
Graylog version is 3.2.3
<img width="1158" alt="Screenshot 2020-10-10 at 14 56 10" src="https://user-images.githubusercontent.com/20798074/95655608-eb48e900-0b08-11eb-81c8-3435db1b4bdc.png">
<img width="2421" alt="Screenshot 2020-10-10 at 14 56 17" src="https://user-images.githubusercontent.com/20798074/95655609-edab4300-0b08-11eb-9265-0c42b0ab1a18.png">

**Comment by mbriquemont** [comment]
> 
> 
> Hey,
> thx for this content pack. Unfortunately it's not working correctly for me.
> It seems the search strings are missing - it just counts all messages or am I wrong:
> Graylog version is 3.2.3
> <img alt="Screenshot 2020-10-10 at 14 56 10" width="1158" src="https://user-images.githubusercontent.com/20798074/95655608-eb48e900-0b08-11eb-81c8-3435db1b4bdc.png">
> <img alt="Screenshot 2020-10-10 at 14 56 17" width="2000" src="https://user-images.githubusercontent.com/20798074/95655609-edab4300-0b08-11eb-9265-0c42b0ab1a18.png">

Hi,
I am the same issue here with GL version 3.3.5+6436f1b.

The widgets.x.configuration.query for the various widgets appears to be missing.

**Comment by schmusch** [comment]
Hi, same for me. Does anyone have a solution so far?

**Comment by schmusch** [comment]
Hi, same for me. Does anyone have a solution so far?

**Comment by flotpg** [comment]
We ended up adding all the search strings manually.

**Comment by c3rberus** [comment]
I have the same issue on 3.3, what do you mean by "adding all the search strings manually"? What steps did you take.

**Comment by c3rberus** [comment]
> @zpfln - In the instructions, it says to create `Beats input (with "Do not add Beats type as prefix" checked)`. If you do not check this, it will add the `winlogbeat_` prefix.
> 
> I have a forked copy of the code with a branch that supports the `winlogbeat_` prefix - https://github.com/SoarinFerret/Graylog_Content_Pack_Active_Directory_Auditing_Dashboards_Beats/tree/winlogbeat-prefix-compatible

This worked for me as well, in my case the fields were prefixed as winlog_ instead of winlogbeat_, a quick find and replace resolved this. Queries for the AD Summary (7d) did not come through, had to add those manually.

**Comment by chris-y** [comment]
The problem with the silly numbers is because the content pack was made for an older version.  Due to changes in Graylog the search strings no longer import.  I've exported from my install, done a search/replace because winlogbeat v7 uses different field names (winlogbeat_winlog_event_id instead of winlogbeat_event_id), re-imported and then created a content pack #4 
That one should work.  It doesn't need the "Do not add Beats type as prefix" ticked - it's easy enough to search/replace that out of the file before import if preferred (less easy to add it back in).
