### ISSUE TITLE
What policy needs to be created?

### ISSUE THREAD

**Issue by Terminator81** [reighnman/Graylog_Content_Pack_Active_Directory_Auditing_Dashboards_Beats#2]
What should the policy look like to generate the logs necessary for these dashboards?

**Comment by SoarinFerret** [comment]
Here is what I am currently using:

![image](https://user-images.githubusercontent.com/33401067/66783430-7d3df780-ee9d-11e9-9173-da0f2dee7e25.png)

However, I'm not seeing any data in the DNS dashboards with the event IDs specified in the template. I'll probably end up tweaking that more as time goes on.

**Comment by Terminator81** [comment]
i have do the same but see not events in the logs ...
do you see a event if you create or delelte users?
